`timescale 1ns/1ps

//=====================================================================
// 16-bit Ripple Carry Adder (Dataflow Style)
// Target Device : xc7a100tcsg324-2 (Artix-7)
//
// Features:
//   - Pure combinational logic
//   - generate-for implementation
//   - No always blocks
//   - No latches
//   - No simulation-only constructs
//   - Explicit carry declaration
//   - Single driver for every carry bit
//=====================================================================

module ripple_carry_adder_16
(
    input  wire [15:0] a,
    input  wire [15:0] b,
    input  wire        cin,

    output wire [15:0] sum,
    output wire        cout
);

    // Explicit 17-bit carry chain
    wire [16:0] carry;

    // Initial carry input
    assign carry[0] = cin;

    // Generate 16 ripple-carry stages
    genvar i;

    generate
        for (i = 0; i < 16; i = i + 1) begin : gen_rca_stage

            // Sum for bit i
            assign sum[i] =
                a[i] ^ b[i] ^ carry[i];

            // Carry generated by bit i
            assign carry[i + 1] =
                (a[i] & b[i]) |
                (a[i] & carry[i]) |
                (b[i] & carry[i]);

        end
    endgenerate

    // Final carry output
    assign cout = carry[16];

endmodule
